### PR TITLE
fixes #50 correctly compute domain counts in Fluo code

### LINKED ISSUE #50: Fluo code incorrectly computing domain counts
While working on #49 I realized the Fluo code may be computing domain counts incorrectly.  I think its computing the number of links to a domain instead of the unique number of URI's seen in a domain.

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

File: modules/data/src/main/java/io/fluo/webindex/data/fluo/UriCountExport.java [hunk 1]
```diff
@@ -31,8 +31,8 @@
 import org.slf4j.LoggerFactory;
 
 public class UriCountExport implements Transmutable<String> {
-  public UriInfo prevCount = UriInfo.EMPTY;
-  public UriInfo newCount = UriInfo.EMPTY;
+  public UriInfo prevCount = UriInfo.ZERO;
```
Comment (mikewalch) [inline modules/data/src/main/java/io/fluo/webindex/data/fluo/UriCountExport.java]: Nice.  That's a better name.
